# Generated by Django 5.1.1 on 2024-10-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.CharField(max_length=500, verbose_name='توضحیات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CO', 'completed'), ('IN', 'inprogress'), ('PE', 'pending')], default='PE', max_length=2, verbose_name='وضعیت')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
