# Generated by Django 5.1.1 on 2024-10-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_module', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'وظیفه', 'verbose_name_plural': 'وظایف'},
        ),
    ]
